### ISSUE TITLE
Ledger Request Objects to json

### ISSUE THREAD

**Issue by ObiajuluM** [mrtnetwork/xrpl_dart#2]
how do i convert the response gotten from getAccountInfo to json.
it returns an accountinfo object instance

**Comment by mrtnetwork** [comment]
> how do i convert the response gotten from getAccountInfo to json. it returns an accountinfo object instance

you can use ```makeCustomCall``` method from ```XRPLRpc``` class

```
  final response = await rpc.makeCustomCall<Map<String, dynamic>>(
        "account_info", [config]);

```

**Comment by ObiajuluM** [comment]
Nice, thanks. It works
