### ISSUE TITLE
Proposal to change name to xrpl-dart or xrpl.js to match the already existing SDK naming convention

### ISSUE THREAD

**Issue by ObiajuluM** [mrtnetwork/xrpl_dart#3]
Would you consider renaming this package to match other XRPL SDK like [xrpl-py](https://github.com/XRPLF/xrpl-py) or [xrpl.js](https://github.com/XRPLF/xrpl.js) to make it easier to find.

Thanks

**Comment by mrtnetwork** [comment]
> Would you consider renaming this package to match other XRPL SDK like [xrpl-py](https://github.com/XRPLF/xrpl-py) or [xrpl.js](https://github.com/XRPLF/xrpl.js) to make it easier to find.
> 
> Thanks

HI
There's no issue with updating the package on GitHub. However, when it comes to pub.dev, the process involves creating a new package on pub.dev and linking the previous package to the updated one.

**Comment by mrtnetwork** [comment]
> > Would you consider renaming this package to match other XRPL SDK like [xrpl-py](https://github.com/XRPLF/xrpl-py) or [xrpl.js](https://github.com/XRPLF/xrpl.js) to make it easier to find.
> > Thanks
> 
> HI There's no issue with updating the package on GitHub. However, when it comes to pub.dev, the process involves creating a new package on pub.dev and linking the previous package to the updated one.

In Dart, package names only accept camelcase without special characters. For the package name, I can modify it to 'xrpl_dart,' or if you have a better suggestion, feel free to share.

**Comment by ObiajuluM** [comment]
> > > Would you consider renaming this package to match other XRPL SDK like [xrpl-py](https://github.com/XRPLF/xrpl-py) or [xrpl.js](https://github.com/XRPLF/xrpl.js) to make it easier to find.
> > > Thanks
> > 
> > 
> > HI There's no issue with updating the package on GitHub. However, when it comes to pub.dev, the process involves creating a new package on pub.dev and linking the previous package to the updated one.
> 
> In Dart, package names only accept camelcase without special characters. For the package name, I can modify it to 'xrpl_dart,' or if you have a better suggestion, feel free to share.

If its not too much trouble 'xrpl_dart' would be nice

**Comment by mrtnetwork** [comment]
> > > > Would you consider renaming this package to match other XRPL SDK like [xrpl-py](https://github.com/XRPLF/xrpl-py) or [xrpl.js](https://github.com/XRPLF/xrpl.js) to make it easier to find.
> > > > Thanks
> > > 
> > > 
> > > HI There's no issue with updating the package on GitHub. However, when it comes to pub.dev, the process involves creating a new package on pub.dev and linking the previous package to the updated one.
> > 
> > 
> > In Dart, package names only accept camelcase without special characters. For the package name, I can modify it to 'xrpl_dart,' or if you have a better suggestion, feel free to share.
> 
> If its not too much trouble 'xrpl_dart' would be nice

Now, that's xrpl_dart!
